// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB17LbQ0T-VS9o4GpAL_y--z42KuerNcaA',
    appId: '1:658467814276:android:91ec8cf8a1c1b31e227bd1',
    messagingSenderId: '658467814276',
    projectId: 'chatapp-flutter-a7213',
    databaseURL: 'https://chatapp-flutter-a7213-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-flutter-a7213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxBMscnnw2PEEZ1rV0-VmyiHINu1UQKnE',
    appId: '1:658467814276:ios:8f9f735265e24169227bd1',
    messagingSenderId: '658467814276',
    projectId: 'chatapp-flutter-a7213',
    databaseURL: 'https://chatapp-flutter-a7213-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-flutter-a7213.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
